export const TEAMS = {
  BLUE: {
    id: 'blue',
    name: 'Blue Team',
    color: 0x3b82f6,
    hexColor: '#3b82f6',
    badgeClass: 'bg-blue-900 text-blue-200 border-blue-500'
  },
  RED: {
    id: 'red',
    name: 'Red Team',
    color: 0xef4444,
    hexColor: '#ef4444',
    badgeClass: 'bg-red-900 text-red-200 border-red-500'
  }
};

export const UNIT_TYPES = {
  swordsman: {
    id: 'swordsman',
    name: 'Swordsman',
    category: 'INFANTRY',
    fightStyle: 'Broadsword Crescent Slash',
    desc: 'Balanced melee warrior with fast sword swings',
    ultimateName: 'Blade Tempest',
    ultimateDesc: 'Triple high-speed forward cleave ending with a ground-splitting overhead slam',
    ultimateCooldown: 9.0,
    cost: 100,
    health: 100,
    moveSpeed: 4.5,
    attackRange: 1.8,
    attackCooldown: 1.2,
    damage: 35,
    scale: 1.0,
    mass: 65,
    iconName: 'Swords'
  },
  spearman: {
    id: 'spearman',
    name: 'Spearman',
    category: 'INFANTRY',
    fightStyle: 'Corinthian Spear Thrust',
    desc: 'Reach melee unit with long spear thrusts',
    ultimateName: 'Gungnir Piercing Blitz',
    ultimateDesc: 'High-velocity lunging spear charge piercing through enemies in a line',
    ultimateCooldown: 9.5,
    cost: 120,
    health: 90,
    moveSpeed: 4.2,
    attackRange: 3.2,
    attackCooldown: 1.4,
    damage: 40,
    scale: 1.05,
    mass: 70,
    iconName: 'Maximize2'
  },
  archer: {
    id: 'archer',
    name: 'Archer',
    category: 'MARTIAL',
    fightStyle: 'Norse Stalker Archery',
    desc: 'Ranged unit, kites away from close threats',
    ultimateName: 'Hail of Arrows',
    ultimateDesc: 'Lofts a rapid volley of arrows raining down on target area',
    ultimateCooldown: 10.0,
    cost: 140,
    health: 75,
    moveSpeed: 4.8,
    attackRange: 18.0,
    preferredRange: 10.0,
    attackCooldown: 2.0,
    damage: 45,
    scale: 0.95,
    mass: 60,
    iconName: 'Target'
  },
  mage: {
    id: 'mage',
    name: 'Mage',
    category: 'ARCANE',
    fightStyle: 'Seiðr Flame Sorcery',
    desc: 'Casts explosive fireballs with AoE blast radius',
    ultimateName: 'Meteor Cataclysm',
    ultimateDesc: 'Channels a colossal celestial blazing meteor that detonates with massive shockwave',
    ultimateCooldown: 13.0,
    cost: 220,
    health: 80,
    moveSpeed: 3.8,
    attackRange: 16.0,
    preferredRange: 9.0,
    attackCooldown: 2.8,
    damage: 75,
    aoeRadius: 4.5,
    scale: 1.0,
    mass: 60,
    iconName: 'Sparkles'
  },
  shield_bearer: {
    id: 'shield_bearer',
    name: 'Shield Bearer',
    category: 'HEAVY',
    fightStyle: 'Aspis Shield Bash & Mace',
    desc: 'High defense front-liner, absorbs hits well',
    ultimateName: 'Aegis Fortress Shockwave',
    ultimateDesc: 'Slams runic tower shield into ground, granting knockback immunity and repelling foes',
    ultimateCooldown: 10.5,
    cost: 180,
    health: 220,
    moveSpeed: 3.2,
    attackRange: 1.6,
    attackCooldown: 1.6,
    damage: 25,
    scale: 1.15,
    mass: 110,
    iconName: 'Shield'
  },
  cavalry: {
    id: 'cavalry',
    name: 'Cavalry',
    category: 'HEAVY',
    fightStyle: 'Jousting Lance Charge',
    desc: 'Fast mounted unit with massive charge knockback',
    ultimateName: 'Valkyrie Trample Charge',
    ultimateDesc: 'Massive turbo speed charge that tramples and tosses enemies high into the air',
    ultimateCooldown: 11.0,
    cost: 300,
    health: 260,
    moveSpeed: 9.0,
    attackRange: 2.4,
    attackCooldown: 1.8,
    damage: 60,
    chargeForce: 1200,
    scale: 1.35,
    mass: 220,
    iconName: 'Zap'
  },
  giant: {
    id: 'giant',
    name: 'Giant',
    category: 'HEAVY',
    fightStyle: 'World Serpent Bone Club',
    desc: 'Massive titanic unit, launches multiple foes in one swing',
    ultimateName: 'Colossal Earth Shatter',
    ultimateDesc: 'Two-handed club earthquake smash sending shockwaves and massive rocks flying',
    ultimateCooldown: 14.0,
    cost: 500,
    health: 850,
    moveSpeed: 2.8,
    attackRange: 3.8,
    attackCooldown: 2.5,
    damage: 110,
    knockbackRadius: 5.0,
    scale: 2.4,
    mass: 450,
    iconName: 'Crown'
  },
  catapult: {
    id: 'catapult',
    name: 'Catapult',
    category: 'SIEGE',
    fightStyle: 'Dwarven Artillery',
    desc: 'Stationary siege engine, lobs heavy boulder for huge AoE blast',
    ultimateName: 'Mega Mortar Salvo',
    ultimateDesc: 'Launches twin flaming incendiary boulders with massive blast radius',
    ultimateCooldown: 14.0,
    cost: 400,
    health: 300,
    moveSpeed: 0.0,
    attackRange: 35.0,
    preferredRange: 20.0,
    attackCooldown: 4.5,
    damage: 140,
    aoeRadius: 7.0,
    scale: 1.8,
    mass: 500,
    iconName: 'Disc'
  },
  battering_ram: {
    id: 'battering_ram',
    name: 'Battering Ram',
    category: 'HEAVY',
    fightStyle: 'Iron-Capped Siege Ram',
    desc: 'Heavy timber siege engine with an iron ram head. Deals colossal damage to gates and castle walls',
    ultimateName: 'Colossal Siege Breaker',
    ultimateDesc: 'Full-throttle hydraulic forward surge pulverizing gates and sending defenders tumbling',
    ultimateCooldown: 12.0,
    cost: 350,
    health: 550,
    moveSpeed: 2.8,
    attackRange: 3.0,
    attackCooldown: 2.6,
    damage: 85,
    structureDamageMultiplier: 5.0,
    scale: 1.5,
    mass: 420,
    iconName: 'Shield'
  },

  // ═══════════════════════════════════════════════════════════════
  // 1. INFANTRY & BLADEMASTERS
  // ═══════════════════════════════════════════════════════════════
  berserker: {
    id: 'berserker',
    name: 'Berserker',
    category: 'INFANTRY',
    fightStyle: 'Dual-Axe Frenzy',
    desc: 'Furious Norse slayer wielding twin bearded axes. Attacks with blistering speed',
    ultimateName: 'Blood Whirlwind',
    ultimateDesc: '360° twin-axe hurricane spinning slash shredding all surrounding foes',
    ultimateCooldown: 9.0,
    cost: 160,
    health: 135,
    moveSpeed: 5.6,
    attackRange: 1.9,
    attackCooldown: 0.75,
    damage: 32,
    scale: 1.05,
    mass: 75,
    iconName: 'Swords'
  },
  samurai: {
    id: 'samurai',
    name: 'Samurai',
    category: 'INFANTRY',
    fightStyle: 'Iaido Katana Mastery',
    desc: 'Disciplined blade master. Delivers razor slashes with lightning Iaido quick-draws',
    ultimateName: 'Iaido Flash Strike',
    ultimateDesc: 'Instant forward flash dash slicing through all enemies in the path',
    ultimateCooldown: 10.0,
    cost: 200,
    health: 125,
    moveSpeed: 5.4,
    attackRange: 2.2,
    attackCooldown: 0.85,
    damage: 52,
    scale: 1.0,
    mass: 70,
    iconName: 'Maximize2'
  },
  gladiator: {
    id: 'gladiator',
    name: 'Gladiator',
    category: 'INFANTRY',
    fightStyle: 'Trident & Retiarius Net',
    desc: 'Arena champion with three-pronged trident and weighted net. Disables and impales',
    ultimateName: 'Net & Impale',
    ultimateDesc: 'Hurls entangling net pinning foes before a vicious triple trident thrust',
    ultimateCooldown: 11.0,
    cost: 175,
    health: 145,
    moveSpeed: 4.8,
    attackRange: 2.6,
    attackCooldown: 1.1,
    damage: 46,
    scale: 1.05,
    mass: 80,
    iconName: 'Target'
  },

  // ═══════════════════════════════════════════════════════════════
  // 2. MARTIAL, ROGUES & ASSASSINS
  // ═══════════════════════════════════════════════════════════════
  assassin: {
    id: 'assassin',
    name: 'Assassin',
    category: 'MARTIAL',
    fightStyle: 'Shadow Twin Daggers',
    desc: 'Silent shadow stalker with twin curved daggers. Extreme agility and lethal backstabs',
    ultimateName: 'Shadow Blink Backstab',
    ultimateDesc: 'Teleports into shadow behind nearest target and executes a lethal 3x critical strike',
    ultimateCooldown: 8.5,
    cost: 185,
    health: 90,
    moveSpeed: 6.4,
    attackRange: 1.6,
    attackCooldown: 0.6,
    damage: 38,
    scale: 0.95,
    mass: 55,
    iconName: 'Zap'
  },
  monk: {
    id: 'monk',
    name: 'Shaolin Monk',
    category: 'MARTIAL',
    fightStyle: 'Chi Fist & Flying Kick',
    desc: 'Spiritual martial artist. Strikes with rapid glowing fist combos and roundhouse kicks',
    ultimateName: 'Dragon Palm Chi Burst',
    ultimateDesc: 'Unleashes a colossal golden kinetic chi shockwave that blows back entire battle lines',
    ultimateCooldown: 10.0,
    cost: 210,
    health: 155,
    moveSpeed: 5.5,
    attackRange: 1.7,
    attackCooldown: 0.65,
    damage: 36,
    scale: 1.0,
    mass: 68,
    iconName: 'Sparkles'
  },
  duelist: {
    id: 'duelist',
    name: 'Duelist',
    category: 'MARTIAL',
    fightStyle: 'Rapier Staccato Fencing',
    desc: 'Master fencer with elegant rapier. Executes pinpoint multi-thrusts with evasive footwork',
    ultimateName: 'Thousand Needles Flurry',
    ultimateDesc: 'Rapid-fire 5-hit piercing barrage finishing with a high-velocity lunging thrust',
    ultimateCooldown: 9.5,
    cost: 195,
    health: 115,
    moveSpeed: 5.6,
    attackRange: 2.4,
    attackCooldown: 0.8,
    damage: 44,
    scale: 1.0,
    mass: 62,
    iconName: 'Crown'
  },
  ninja: {
    id: 'ninja',
    name: 'Ninja',
    category: 'MARTIAL',
    fightStyle: 'Shuriken & Ninjato',
    desc: 'Shinobi skirmisher. Hurls rapid steel shurikens from range and slices in close quarters',
    ultimateName: 'Shuriken Storm',
    ultimateDesc: 'Vanishes in smoke and unleashes an 8-way lethal steel shuriken barrage',
    ultimateCooldown: 9.0,
    cost: 215,
    health: 95,
    moveSpeed: 5.8,
    attackRange: 12.0,
    preferredRange: 6.5,
    attackCooldown: 1.0,
    damage: 32,
    scale: 0.95,
    mass: 58,
    iconName: 'Disc'
  },

  // ═══════════════════════════════════════════════════════════════
  // 3. HOLY, DARK & ARCANE
  // ═══════════════════════════════════════════════════════════════
  paladin: {
    id: 'paladin',
    name: 'Paladin',
    category: 'HOLY',
    fightStyle: 'Divine Warhammer',
    desc: 'Holy knight in blessed plate armor wielding a colossal two-handed warhammer',
    ultimateName: 'Heavenly Smite',
    ultimateDesc: 'Summons a colossal pillar of divine golden light crashing from the heavens with radial stun',
    ultimateCooldown: 12.0,
    cost: 280,
    health: 310,
    moveSpeed: 3.6,
    attackRange: 2.3,
    attackCooldown: 1.5,
    damage: 72,
    scale: 1.15,
    mass: 120,
    iconName: 'Shield'
  },
  necromancer: {
    id: 'necromancer',
    name: 'Necromancer',
    category: 'ARCANE',
    fightStyle: 'Death Scythe & Soul Drain',
    desc: 'Dark grim summoner wielding a sinister scythe. Drains enemy life to heal himself',
    ultimateName: 'Soul Harvest',
    ultimateDesc: 'Erupts a dark void vortex that siphons life from all nearby foes and heals caster',
    ultimateCooldown: 13.0,
    cost: 260,
    health: 110,
    moveSpeed: 3.8,
    attackRange: 14.0,
    preferredRange: 8.0,
    attackCooldown: 2.0,
    damage: 55,
    scale: 1.0,
    mass: 60,
    iconName: 'Sparkles'
  },
  pyromancer: {
    id: 'pyromancer',
    name: 'Pyromancer',
    category: 'ARCANE',
    fightStyle: 'Inferno Flame Blast',
    desc: 'Master of flame wielding volcanic gauntlets. Shoots rapid firebolts and erupts flame',
    ultimateName: 'Inferno Cataclysm',
    ultimateDesc: 'Summons erupting magma pillars beneath enemies that leave burning scorch craters',
    ultimateCooldown: 11.5,
    cost: 250,
    health: 95,
    moveSpeed: 4.0,
    attackRange: 15.0,
    preferredRange: 8.5,
    attackCooldown: 1.5,
    damage: 52,
    aoeRadius: 3.2,
    scale: 1.0,
    mass: 62,
    iconName: 'Flame'
  },
  frost_witch: {
    id: 'frost_witch',
    name: 'Frost Witch',
    category: 'ARCANE',
    fightStyle: 'Glacial Ice Magic',
    desc: 'Glacial sorceress wielding a crystalline ice staff. Fires piercing icicles that freeze foes',
    ultimateName: 'Glacial Spikes Blizzard',
    ultimateDesc: 'Erupts jagged frozen ice stalagmites from the ground, freezing enemies solid',
    ultimateCooldown: 12.0,
    cost: 240,
    health: 95,
    moveSpeed: 3.9,
    attackRange: 16.0,
    preferredRange: 9.0,
    attackCooldown: 1.6,
    damage: 50,
    scale: 0.98,
    mass: 58,
    iconName: 'Sparkles'
  },

  // ═══════════════════════════════════════════════════════════════
  // 4. HEAVY, BEASTS & TITANS
  // ═══════════════════════════════════════════════════════════════
  dragon_knight: {
    id: 'dragon_knight',
    name: 'Dragon Knight',
    category: 'HEAVY',
    fightStyle: 'Flaming Zweihänder',
    desc: 'Heavy dragon-scaled warrior wielding a flaming two-handed Greatsword',
    ultimateName: 'Dragon Flame Breath',
    ultimateDesc: 'Exhales a continuous sweeping cone of incandescent dragon flame incinerating foes',
    ultimateCooldown: 11.0,
    cost: 320,
    health: 380,
    moveSpeed: 3.8,
    attackRange: 2.6,
    attackCooldown: 1.6,
    damage: 82,
    scale: 1.25,
    mass: 150,
    iconName: 'Crown'
  },
  golem: {
    id: 'golem',
    name: 'Runic Golem',
    category: 'HEAVY',
    fightStyle: 'Stone Fists & Boulder Lob',
    desc: 'Colossal ancient stone automaton. Immune to knockdown, hits with earthquake fists',
    ultimateName: 'Seismic Boulder Hurl',
    ultimateDesc: 'Rips an enormous boulder out of the earth and hurls it with devastating blast',
    ultimateCooldown: 13.0,
    cost: 420,
    health: 680,
    moveSpeed: 2.6,
    attackRange: 2.8,
    attackCooldown: 2.2,
    damage: 95,
    scale: 1.6,
    mass: 380,
    iconName: 'Disc'
  },

  // ═══════════════════════════════════════════════════════════════
  // 5. DEITIES, GODS & MYTHIC BOSSES
  // ═══════════════════════════════════════════════════════════════
  zeus: {
    id: 'zeus',
    name: 'Zeus',
    title: 'Lord of the Heavens & Storms',
    category: 'DEITY',
    isBoss: true,
    fightStyle: 'Olympian Thunder & Aegis Smite',
    desc: 'Supreme god of Olympus. Wields crackling master thunderbolts and golden Aegis shield. Immune to knockdown.',
    ultimateName: 'Wrath of Olympus',
    ultimateDesc: 'Calls down a barrage of celestial lightning strikes from the heavens, blasting craters and electrifying whole platoons',
    ultimateCooldown: 12.0,
    cost: 850,
    health: 1650,
    moveSpeed: 3.6,
    attackRange: 22.0,
    preferredRange: 12.0,
    attackCooldown: 1.8,
    damage: 135,
    aoeRadius: 4.8,
    scale: 2.2,
    mass: 420,
    iconName: 'Zap'
  },
  ares: {
    id: 'ares',
    name: 'Ares',
    title: 'God of Savage War & Slaughter',
    category: 'DEITY',
    isBoss: true,
    fightStyle: 'Executioner Greatblade & Blood Roar',
    desc: 'Towering avatar of blood and battle. Swings a colossal hellfire Greatblade that flings squads like ragdolls.',
    ultimateName: "Blood God's Rampage",
    ultimateDesc: 'Leaps high into the sky and smashes down in an apocalyptic blood-fire eruption, shattering ground and toppling armies',
    ultimateCooldown: 11.0,
    cost: 920,
    health: 1950,
    moveSpeed: 3.8,
    attackRange: 4.2,
    attackCooldown: 1.7,
    damage: 165,
    knockbackRadius: 6.5,
    scale: 2.5,
    mass: 550,
    iconName: 'Crown'
  },
  hades: {
    id: 'hades',
    name: 'Hades',
    title: 'Lord of the Underworld & Dead',
    category: 'DEITY',
    isBoss: true,
    fightStyle: 'Soulreaper Bident & Shadow Siphon',
    desc: 'Grim sovereign of the underworld. Wields a necrotic bident scythe that reaps souls and siphons life from victims.',
    ultimateName: 'Underworld Soul Eruption',
    ultimateDesc: 'Impales the earth to unleash spiraling necrotic soul vortexes and rising obsidian spikes that terrify and crush enemies',
    ultimateCooldown: 13.0,
    cost: 880,
    health: 1550,
    moveSpeed: 3.5,
    attackRange: 18.0,
    preferredRange: 10.0,
    attackCooldown: 2.0,
    damage: 125,
    aoeRadius: 4.2,
    scale: 2.1,
    mass: 390,
    iconName: 'Ghost'
  },
  poseidon: {
    id: 'poseidon',
    name: 'Poseidon',
    title: 'Earthshaker & Ocean Sovereign',
    category: 'DEITY',
    isBoss: true,
    fightStyle: 'Titan Trident & Tsunami Surge',
    desc: 'Colossal lord of the abyss and seismic depths. Slams the ground with a massive glowing trident, erupting geysers.',
    ultimateName: 'Abyssal Tsunami & Earthshaker',
    ultimateDesc: 'Triggers a sequence of catastrophic high-pressure geysers and tidal shockwaves that wash entire armies away',
    ultimateCooldown: 12.5,
    cost: 900,
    health: 1750,
    moveSpeed: 3.5,
    attackRange: 5.5,
    attackCooldown: 2.1,
    damage: 145,
    aoeRadius: 5.0,
    scale: 2.3,
    mass: 480,
    iconName: 'Waves'
  }
};
